"""Persist checkout sessions to prevent duplicate subscriptions

Revision ID: 9831ce1317d3
Revises: fd0384d34e8a
"""

import sqlalchemy as sa
from alembic import op

revision = "9831ce1317d3"
down_revision = "fd0384d34e8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("checkout_session_id", sa.String(length=150), nullable=True))
    op.add_column("users", sa.Column("checkout_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "checkout_expires_at")
    op.drop_column("users", "checkout_session_id")
    # ### end Alembic commands ###
