"""Initial paid service schema

Revision ID: fd0384d34e8a
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "fd0384d34e8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_events",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_tokens",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(op.f("ix_login_tokens_email"), "login_tokens", ["email"], unique=False)
    op.create_table(
        "rate_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_events_created_at"), "rate_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_rate_events_key"), "rate_events", ["key"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("stripe_customer", sa.String(length=100), nullable=True),
        sa.Column("subscription_id", sa.String(length=100), nullable=True),
        sa.Column("subscription_status", sa.String(length=30), nullable=False),
        sa.Column("subscription_until", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_customer"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "connections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("pair_digest", sa.String(length=64), nullable=True),
        sa.Column("pair_expires", sa.DateTime(), nullable=True),
        sa.Column("bridge_digest", sa.String(length=64), nullable=True),
        sa.Column("bridge_expires", sa.DateTime(), nullable=True),
        sa.Column("account_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("account_label", sa.String(length=100), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("next_request_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pair_digest"),
    )
    op.create_index(
        op.f("ix_connections_bridge_digest"), "connections", ["bridge_digest"], unique=True
    )
    op.create_index(op.f("ix_connections_user_id"), "connections", ["user_id"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credentials_digest"), "credentials", ["digest"], unique=True)
    op.create_index(op.f("ix_credentials_user_id"), "credentials", ["user_id"], unique=False)
    op.create_table(
        "searches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("connection_id", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("plans", sa.JSON(), nullable=False),
        sa.Column("provider_calls", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_searches_created_at"), "searches", ["created_at"], unique=False)
    op.create_index(op.f("ix_searches_user_id"), "searches", ["user_id"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("search_id", sa.String(length=32), nullable=False),
        sa.Column("offer_id", sa.String(length=200), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["search_id"], ["searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("search_id", "offer_id"),
    )
    op.create_index(op.f("ix_quotes_search_id"), "quotes", ["search_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("search_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_digest", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["search_id"], ["searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_search_id"), "tasks", ["search_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_search_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_quotes_search_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_searches_user_id"), table_name="searches")
    op.drop_index(op.f("ix_searches_created_at"), table_name="searches")
    op.drop_table("searches")
    op.drop_index(op.f("ix_credentials_user_id"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_digest"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_connections_user_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_bridge_digest"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_rate_events_key"), table_name="rate_events")
    op.drop_index(op.f("ix_rate_events_created_at"), table_name="rate_events")
    op.drop_table("rate_events")
    op.drop_index(op.f("ix_login_tokens_email"), table_name="login_tokens")
    op.drop_table("login_tokens")
    op.drop_table("billing_events")
    # ### end Alembic commands ###
